require 'forwardable'
require 'wapiti'

require 'anystyle/version'
require 'anystyle/errors'
require 'anystyle/utils'
require 'anystyle/dictionary'

require 'anystyle/feature'
require 'anystyle/feature/affix'
require 'anystyle/feature/canonical'
require 'anystyle/feature/caps'
require 'anystyle/feature/category'
require 'anystyle/feature/dictionary'
require 'anystyle/feature/keyword'
require 'anystyle/feature/locator'
require 'anystyle/feature/number'
require 'anystyle/feature/position'
require 'anystyle/feature/punctuation'

require 'anystyle/normalizer'
require 'anystyle/normalizer/locale'
require 'anystyle/normalizer/location'
require 'anystyle/normalizer/locator'
require 'anystyle/normalizer/names'
require 'anystyle/normalizer/page'
require 'anystyle/normalizer/punctuation'
require 'anystyle/normalizer/quotes'
require 'anystyle/normalizer/type'

require 'anystyle/parser'
